<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="2" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="23204" started-at="2021-06-26T07:14:41 IST" finished-at="2021-06-26T07:15:04 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="23204" started-at="2021-06-26T07:14:41 IST" finished-at="2021-06-26T07:15:04 IST">
      <class name="org.tests.com.TC03">
        <test-method status="PASS" signature="setup()[pri:0, instance:org.tests.com.TC03@548ad73b]" name="setup" is-config="true" duration-ms="11032" started-at="2021-06-26T07:14:42 IST" finished-at="2021-06-26T07:14:53 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testCase03()[pri:0, instance:org.tests.com.TC03@548ad73b]" name="testCase03" duration-ms="4" started-at="2021-06-26T07:14:53 IST" description="This is Test Case03" finished-at="2021-06-26T07:14:53 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase03 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.tests.com.TC03@548ad73b]" name="quit" is-config="true" duration-ms="573" started-at="2021-06-26T07:14:53 IST" finished-at="2021-06-26T07:14:54 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- org.tests.com.TC03 -->
      <class name="org.tests.com.AA">
        <test-method status="PASS" signature="setup()[pri:0, instance:org.tests.com.AA@4c762604]" name="setup" is-config="true" duration-ms="10566" started-at="2021-06-26T07:14:42 IST" finished-at="2021-06-26T07:14:52 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="aaTestCase()[pri:0, instance:org.tests.com.AA@4c762604]" name="aaTestCase" duration-ms="36" retried="true" started-at="2021-06-26T07:14:52 IST" description="This is AA Test" finished-at="2021-06-26T07:14:52 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at org.tests.com.AA.aaTestCase(AA.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aaTestCase -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.tests.com.AA@4c762604]" name="quit" is-config="true" duration-ms="587" started-at="2021-06-26T07:14:52 IST" finished-at="2021-06-26T07:14:53 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="setup()[pri:0, instance:org.tests.com.AA@4c762604]" name="setup" is-config="true" duration-ms="4740" started-at="2021-06-26T07:14:53 IST" finished-at="2021-06-26T07:14:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="aaTestCase()[pri:0, instance:org.tests.com.AA@4c762604]" name="aaTestCase" duration-ms="12" retried="true" started-at="2021-06-26T07:14:58 IST" description="This is AA Test" finished-at="2021-06-26T07:14:58 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at org.tests.com.AA.aaTestCase(AA.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aaTestCase -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.tests.com.AA@4c762604]" name="quit" is-config="true" duration-ms="592" started-at="2021-06-26T07:14:58 IST" finished-at="2021-06-26T07:14:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="setup()[pri:0, instance:org.tests.com.AA@4c762604]" name="setup" is-config="true" duration-ms="5149" started-at="2021-06-26T07:14:58 IST" finished-at="2021-06-26T07:15:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="aaTestCase()[pri:0, instance:org.tests.com.AA@4c762604]" name="aaTestCase" duration-ms="12" started-at="2021-06-26T07:15:03 IST" description="This is AA Test" finished-at="2021-06-26T07:15:03 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at org.tests.com.AA.aaTestCase(AA.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aaTestCase -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.tests.com.AA@4c762604]" name="quit" is-config="true" duration-ms="713" started-at="2021-06-26T07:15:04 IST" finished-at="2021-06-26T07:15:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- org.tests.com.AA -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
